### ISSUE TITLE
Seems to crash when make crashes

### ISSUE THREAD

**Issue by gampleman** [quarterto/watch-make#3]
If make exits with an error, watch-make seems to crash. Is this intentional?

**Comment by apaleslimghost** [comment]
that's a known issue (#2), caused by me misinterpreting the make documentation 😅 

the fix is nontrivial, we'd have to parse the last line of make output to get the actual error code.

**Comment by apaleslimghost** [comment]
@gampleman watch-make 2 has been released, which is a rewrite in javascript. it addresses this issue among others. check it out

**Comment by gampleman** [comment]
Looks pretty cool! Does it expose an API to other modules? (I'd build a live-reload server on top of this)

**Comment by apaleslimghost** [comment]
Not currently. I'm not sure building on top of watch-make would be the way to go for that; watch-make watches your prerequisites, but a server would have to watch your targets.

**Comment by apaleslimghost** [comment]
Although you could maybe do it within your makefile with [make-livereload](https://github.com/mklabs/make-livereload) (I think it would work with `wmake reload`).

**Comment by gampleman** [comment]
The strategy I use currently is that I watch the prerequisites (currently I specify them manually, but having access to those programatically from the makefile would be much nicer), run make when they change, then trigger the livereload server when make completes. In theory that could be wasteful, since make could result in no new targets, but in practice that hasn't happened to me yet.
